language: go

go:
  - 1.12.x
  - 1.13.x

install: true

script:
  - go mod tidy && git diff --no-patch --exit-error
  - go test -v -race -cover -coverpkg=./... -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
