name: build
on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-build:
    name: 👷 Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.18, 1.19, 1.20, 1.21]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint and Test via ${{ matrix.goVer }}
        env:
          STREAM_API_KEY: ${{ secrets.STREAM_API_KEY }}
          STREAM_API_SECRET: ${{ secrets.STREAM_API_SECRET }}
          STREAM_API_REGION: ${{ secrets.STREAM_API_REGION }}
          STREAM_API_VERSION: ${{ secrets.STREAM_API_VERSION }}
        run: |
          go mod tidy -v && git diff --no-patch --exit-code
          go test -v -race ./...
