name: build
on:
  push:
    branches:
      - 'master'
  pull_request:
jobs:
  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.15, 1.16]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint and Test via ${{ matrix.goVer }}
        env:
          STREAM_API_KEY: ${{ secrets.STREAM_API_KEY }}
          STREAM_API_SECRET: ${{ secrets.STREAM_API_SECRET }}
          STREAM_API_REGION: ${{ secrets.STREAM_API_REGION }}
          STREAM_API_VERSION: ${{ secrets.STREAM_API_VERSION }}
        run: |
          go mod tidy -v && git diff --no-patch --exit-code
          ./run-lint.sh
          go test -v -race ./...

      - name: Build on ${{ matrix.goVer }}
        run: go build ./...
